var WELL = {
	name:'well',
	query:[
		'ID_WELL INT AUTO_INCREMENT PRIMARY KEY',
		'STRT VARCHAR(50) NOT NULL', 
		'STOP VARCHAR(50) NOT NULL', 
		'STEP VARCHAR(50) NOT NULL',
		'SRVC1 VARCHAR(50) NOT NULL', 
		'DATEE VARCHAR(50) NOT NULL', 
		'WELL VARCHAR(50) NOT NULL', 
		'COMP VARCHAR(50) NOT NULL', 
		'FLD VARCHAR(50) NOT NULL', 
		'LOC VARCHAR(50) NOT NULL', 
		'LATI VARCHAR(50) NOT NULL', 
		'LONGG VARCHAR(50) NOT NULL', 
		'RWS VARCHAR(50) NOT NULL', 
		'WST VARCHAR(50) NOT NULL', 
		'PROV VARCHAR(50) NOT NULL',
		'SRVC2 VARCHAR(50) NOT NULL',
		'ID_LINK INT AUTO_INCREMENT PRIMARY KEY',
		'FOREIGN KEY (ID_LINK) REFERENCES link(ID_LINK)'
		],
	field:['STRT', 'STOP', 'STEP', 'SRVC1', 'DATEE', 'WELL', 'COMP', 'FLD', 'LOC', 'LATI', 'LONGG', 'RWS', 'WST', 'PROV', 'SRVC2']
}
module.exports.well = WELL;