module.exports = function (sequelize, DataTypes) {
    return sequelize.define('family',{
        idFamily:{
            type:DataTypes.INTEGER,
            primaryKey:true,
            unique:true
        },
        name:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        familyGroup:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        unit:{
            type:DataTypes.STRING(10),
            allowNull:false
        },
        minScale:{
            type:DataTypes.FLOAT,
            allowNull:false
        },
        maxScale:{
            type:DataTypes.FLOAT,
            allowNull:false
        },
        displayType:{
            type:DataTypes.STRING(30),
            allowNull:false
        },
        displayMode:{
            type:DataTypes.STRING(30),
            allowNull:false,
        },
        blockPosition:{
            type:DataTypes.STRING(30),
            allowNull:false,
        },
        lineStyle:{
            type:DataTypes.STRING(30),
            allowNull:false
        },
        lineWidth:{
            type:DataTypes.INTEGER,
            allowNull:false
        },
        lineColor:{
            type:DataTypes.STRING(30),
            allowNull:false
        }

    });
};
