module.exports = function (sequelize, DataTypes) {
    return sequelize.define('well_data',{
        idWell: {
            type:DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey:true
        },
        STRT:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        STOP:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        step:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        SRVC1:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        DATEE:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        WELL:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        COMP:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        FLD:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        LOC:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        LATI:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        LONGG:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        RWS:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        WST:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        PROV:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        SRVC2:{
            type:DataTypes.STRING(50),
            allowNull:false
        },
        idLink:DataTypes.INTEGER
    });
};
